const Elements = {
  Email: {
    label: "Email",
    name: "email",
    type: "email",
    placeholder: "Email",
    required: true,
    controlId: "formBasicEmail",
  },
  Password: {
    label: "Password",
    name: "password",
    type: "password",
    placeholder: "Password",
    required: true,
    controlId: "formBasicPassword",
  },
  ConfirmPassword: {
    label: "Confirm Password",
    name: "confirmPassword",
    type: "password",
    placeholder: "ConfirmPassword",
    required: true,
    controlId: "formBasicConfirmPassword",
  },
  Name: {
    label: "Name",
    name: "name",
    type: "text",
    placeholder: "Name",
    required: true,
    controlId: "formBasicName",
  },
  Price: {
    label: "Price",
    name: "price",
    type: "number",
    placeholder: "Price",
    required: true,
    controlId: "formBasicPrice",
  },
  Author: {
    label: "Author",
    name: "author",
    type: "text",
    placeholder: "Author",
    required: true,
    controlId: "formBasicAuthor",
  },
  Classification: {
    label: "Classification",
    name: "classification",
    type: "text",
    placeholder: "Classification",
    required: true,
    controlId: "formBasicClassification",
  },
  Language: {
    label: "Language",
    name: "language",
    type: "text",
    placeholder: "Language",
    required: true,
    controlId: "formBasicLanguage",
  },
  Isbn: {
    label: "Isbn",
    name: "isbn",
    type: "number",
    placeholder: "Isbn",
    required: true,
    controlId: "formBasicIsbn",
  },
  Description: {
    type: "textarea",
    label: "Description",
    name: "description",
    placeholder: "Description",
    required: true,
    controlId: "formBasicDescription",
  },
  Message: {
    type: "textarea",
    label: "Message",
    name: "message",
    placeholder: "Message",
    required: true,
    controlId: "formBasicMessage",
  },
  Image: {
    type: "file",
    label: "Upload Image",
    placeholder: "Select Image",
    required: true,
    controlId: "formBasicImage",
  },
  Images: {
    type: "file",
    label: "Upload Images",
    name: "images",
    placeholder: "Select Images",
    required: true,
    controlId: "formBasicImages",
  },
  PublishedYear: {
    type: "number",
    label: "PublishedYear",
    name: "publishedYear",
    placeholder: "PublishedYear",
    required: true,
    controlId: "formBasicPublishedYear",
  },
  Title: {
    type: "text",
    label: "Title",
    name: "title",
    placeholder: "Title",
    required: true,
    controlId: "formBasicTitle",
  },
  Time: {
    type: "text",
    label: "Time",
    name: "time",
    placeholder: "Time",
    required: true,
    controlId: "formBasicTime",
  },
  Code: {
    type: "number",
    label: "Code",
    name: "code",
    placeholder: "Enter Code",
    required: true,
    controlId: "formBasicCode",
  },
  Otp: {
    type: "number",
    label: "Otp",
    name: "otp",
    placeholder: "Enter otp",
    required: true,
    controlId: "formBasicOtp",
  },
  Phone: {
    type: "number",
    label: "Phone",
    name: "phone",
    placeholder: "Enter Phone",
    required: true,
    controlId: "formBasicPhone",
  },
  PinCode: {
    type: "number",
    label: "PinCode",
    name: "pincode",
    placeholder: "Enter PinCode",
    required: true,
    controlId: "formBasicPinCode",
  },
  Locality: {
    type: "text",
    label: "Locality",
    name: "locality",
    placeholder: "Enter Locality",
    required: true,
    controlId: "formBasicLocality",
  },
  Address: {
    type: "text",
    label: "Address",
    name: "address",
    placeholder: "Enter Address",
    required: true,
    controlId: "formBasicAddress",
  },
  City: {
    type: "text",
    label: "City",
    name: "city",
    placeholder: "Enter City",
    required: true,
    controlId: "formBasicCity",
  },
  State: {
    type: "text",
    label: "State",
    name: "state",
    placeholder: "Enter State",
    required: true,
    controlId: "formBasicState",
  },
};

export const ContactFields = [Elements.Name, Elements.Email, Elements.Message];
export const LoginFields = [Elements.Email, Elements.Password];
export const RegistrationFields = [Elements.Email, Elements.Password];
export const VerifyFormFields = [Elements.Email, Elements.Code];
export const AddressFormFields = [
  Elements.Name,
  Elements.Phone,
  Elements.PinCode,
  Elements.Locality,
  Elements.Address,
  Elements.City,
  Elements.State,
];

export const ForgotPasswordFields = [Elements.Email];
export const VerifyForgotPasswordFields = [
  Elements.Email,
  Elements.Otp,
  Elements.Password,
  Elements.ConfirmPassword,
];
